### ISSUE TITLE
Problema ao executar em debug.

### ISSUE THREAD

**Issue by laffsj** [ezequieljuliano/Mailer4Delphi#3]
Ezequiel gostaria de relatar um problema que tive.
Ao executar testes com o mapi, em modo debug e com o outlook aberto, ele enviou direto e não me mostrou a tela do email, já com o outlook fechado, ele carrega a tela par eu preencher os dados. Em release esta normal.
Gostaria de ver com você também sobre o anexo se seria possível deixar somente o nome do arquivo e não o caminho com o nome como esta mostrando.
Obrigado.

**Comment by laffsj** [comment]
A questão do nome consegui resolver, se puder dar sugestão mude a linha:
a^.lpszFileName := StrNew(PAnsiChar(AnsiString(GetAttachments.Strings[i])));
para:
a^.lpszFileName := StrNew(PAnsiChar(AnsiString(ExtractFileName(GetAttachments.Strings[i]))));

**Comment by ezequieljuliano** [comment]
Você consegue enviar via PR esta alteração, assim consigo juntar ao projeto após code review?
